name: raahein_final
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flare_flutter:
    path: /home/aayush/Raahein/raahein_final/flare_flutter

  cupertino_icons: ^0.1.2
  provider: ^2.0.0
  audioplayers: ^0.7.8
  curved_navigation_bar: ^0.3.0
  share: ^0.6.2+1
  location: ^2.3.5
  razorpay_flutter: ^1.1.1
  fluttertoast: ^3.1.0
  barcode_scan: ^1.0.0
  gradient_widgets: 
  geocoder: ^0.2.1
  google_maps_flutter: ^0.5.20+3
  http: ^0.12.0+2
  cloud_firestore: any
  firebase_auth: ^0.14.0+2
  firebase_database: ^3.0.5
  rxdart: ^0.22.1+1
  geoflutterfire: ^2.0.3+5
  google_maps_webservice: ^0.0.14
  rflutter_alert: ^1.0.2
  geolocator: ^5.1.2
  firebase_core:
  google_sign_in: ^4.0.1+3 
  


dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/pic1.png
   - assets/pic2.png
   - assets/pic3.png
   - assets/pic4.png
   - assets/pic5.png
   - assets/pic6.png
   - assets/back.png
   - assets/iauto.png
   - assets/breakdown.jpg
   - assets/apparel_house-01.jpeg
   - assets/kanhai_colony-01.jpeg
   - assets/ramada-01.jpeg
   - assets/huda_city-01.jpeg
   - assets/images/background/background.jpg
   - assets/images/background/background2.jpg
   - assets/levels.json
   - assets/images/borders/border_1.png
   - assets/images/borders/border_2.png
   - assets/images/borders/border_3.png
   - assets/images/borders/border_4.png
   - assets/images/borders/border_5.png
   - assets/images/borders/border_7.png
   - assets/images/borders/border_8.png
   - assets/images/borders/border_10.png
   - assets/images/borders/border_11.png
   - assets/images/borders/border_12.png
   - assets/images/borders/border_13.png
   - assets/images/borders/border_14.png
   - assets/images/borders/border_15.png
   - assets/images/tiles/blue.png
   - assets/images/tiles/green.png
   - assets/images/tiles/orange.png
   - assets/images/tiles/purple.png
   - assets/images/tiles/red.png
   - assets/images/tiles/yellow.png
   - assets/images/tiles/multicolor.png
   - assets/images/deco/wall.png
   - assets/images/deco/ice_01.png
   - assets/images/deco/ice_02.png
   - assets/images/bombs/blue.png
   - assets/images/bombs/green.png
   - assets/images/bombs/orange.png
   - assets/images/bombs/purple.png
   - assets/images/bombs/red.png
   - assets/images/bombs/yellow.png
   - assets/images/bombs/fireball.png
   - assets/images/bombs/multi_color.png
   - assets/images/bombs/mine.png
   - assets/images/bombs/tnt.png
   - assets/images/bombs/rocket.png
   - assets/audio/swap.wav
   - assets/audio/move_down.wav
   - assets/audio/bomb.wav
   - assets/audio/game_start.wav
   - assets/audio/win.wav
   - assets/audio/lost.wav
   - assets/images/combo.png
   - assets/my_icon.png
   - assets/
   - assets/popup.png
   - assets/final.gif
   - assets/pay3.gif
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  #   - family: RobotoMedium
  #     fonts:
  #       - asset: assets/Nunito-Regular.ttf
  # #       - asset: fonts/Schyler-Italic.ttf
  # #         style: italic
    - family: Nunito
      fonts:
        - asset: assets/Nunito-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
