name: teddy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter:
    path: ../../flare_flutter
  firebase_core: 
  firebase_auth: 
  google_sign_in: ^4.0.1+3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
  assets:
    - assets/